name: Build

on:

  push:

    branches:

      - main

  pull_request:

    branches:

      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository

        uses: actions/checkout@v2

      - name: Set up C++ Compiler

        uses: actions/setup-cmake@v1

        with:

          cmake-version: '3.x' # Insira a versão do CMake que você deseja usar

      - name: Build Project

        run: |

          mkdir build

          cd build

          cmake ..

          make

      # Se necessário, adicione etapas adicionais, como testes ou empacotamento do seu sistema operacional.

